[2020-04-04 22:58:59 -0400] [7211] [INFO] Starting gunicorn 20.0.4
[2020-04-04 22:58:59 -0400] [7211] [INFO] Listening at: http://127.0.0.1:8000 (7211)
[2020-04-04 22:58:59 -0400] [7211] [INFO] Using worker: sync
[2020-04-04 22:58:59 -0400] [7216] [INFO] Booting worker with pid: 7216
[2020-04-04 22:58:59 -0400] [7217] [INFO] Booting worker with pid: 7217
[2020-04-04 22:59:00 -0400] [7216] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ehzhang/PicassoXS/src/backend/flask_app/__init__.py", line 21, in <module>
    import flask_app.views  # noqa: E402  pylint: disable=wrong-import-position
  File "/home/ehzhang/PicassoXS/src/backend/flask_app/views/__init__.py", line 2, in <module>
    from flask_app.views.index import upload_img, index
  File "/home/ehzhang/PicassoXS/src/backend/flask_app/views/index.py", line 9, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
[2020-04-04 22:59:00 -0400] [7216] [INFO] Worker exiting (pid: 7216)
[2020-04-04 22:59:00 -0400] [7217] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ehzhang/PicassoXS/src/backend/flask_app/__init__.py", line 21, in <module>
    import flask_app.views  # noqa: E402  pylint: disable=wrong-import-position
  File "/home/ehzhang/PicassoXS/src/backend/flask_app/views/__init__.py", line 2, in <module>
    from flask_app.views.index import upload_img, index
  File "/home/ehzhang/PicassoXS/src/backend/flask_app/views/index.py", line 9, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
[2020-04-04 22:59:00 -0400] [7217] [INFO] Worker exiting (pid: 7217)
[2020-04-04 23:00:22 -0400] [7267] [INFO] Starting gunicorn 20.0.4
[2020-04-04 23:00:22 -0400] [7267] [INFO] Listening at: http://127.0.0.1:8000 (7267)
[2020-04-04 23:00:22 -0400] [7267] [INFO] Using worker: sync
[2020-04-04 23:00:22 -0400] [7271] [INFO] Booting worker with pid: 7271
[2020-04-04 23:00:22 -0400] [7272] [INFO] Booting worker with pid: 7272
[2020-04-04 23:00:22 -0400] [7271] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ehzhang/PicassoXS/src/backend/flask_app/__init__.py", line 21, in <module>
    import flask_app.views  # noqa: E402  pylint: disable=wrong-import-position
  File "/home/ehzhang/PicassoXS/src/backend/flask_app/views/__init__.py", line 2, in <module>
    from flask_app.views.index import upload_img, index
  File "/home/ehzhang/PicassoXS/src/backend/flask_app/views/index.py", line 10, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2020-04-04 23:00:22 -0400] [7271] [INFO] Worker exiting (pid: 7271)
[2020-04-04 23:00:22 -0400] [7272] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ehzhang/PicassoXS/src/backend/flask_app/__init__.py", line 21, in <module>
    import flask_app.views  # noqa: E402  pylint: disable=wrong-import-position
  File "/home/ehzhang/PicassoXS/src/backend/flask_app/views/__init__.py", line 2, in <module>
    from flask_app.views.index import upload_img, index
  File "/home/ehzhang/PicassoXS/src/backend/flask_app/views/index.py", line 10, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2020-04-04 23:00:22 -0400] [7272] [INFO] Worker exiting (pid: 7272)
[2020-04-04 23:01:06 -0400] [7293] [INFO] Starting gunicorn 20.0.4
[2020-04-04 23:01:06 -0400] [7293] [INFO] Listening at: http://127.0.0.1:8000 (7293)
[2020-04-04 23:01:06 -0400] [7293] [INFO] Using worker: sync
[2020-04-04 23:01:06 -0400] [7298] [INFO] Booting worker with pid: 7298
[2020-04-04 23:01:06 -0400] [7299] [INFO] Booting worker with pid: 7299
[2020-04-04 23:01:06 -0400] [7299] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ehzhang/PicassoXS/src/backend/flask_app/__init__.py", line 21, in <module>
    import flask_app.views  # noqa: E402  pylint: disable=wrong-import-position
  File "/home/ehzhang/PicassoXS/src/backend/flask_app/views/__init__.py", line 2, in <module>
    from flask_app.views.index import upload_img, index
  File "/home/ehzhang/PicassoXS/src/backend/flask_app/views/index.py", line 13, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
[2020-04-04 23:01:06 -0400] [7299] [INFO] Worker exiting (pid: 7299)
[2020-04-04 23:01:06 -0400] [7298] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ehzhang/PicassoXS/src/backend/env/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ehzhang/PicassoXS/src/backend/flask_app/__init__.py", line 21, in <module>
    import flask_app.views  # noqa: E402  pylint: disable=wrong-import-position
  File "/home/ehzhang/PicassoXS/src/backend/flask_app/views/__init__.py", line 2, in <module>
    from flask_app.views.index import upload_img, index
  File "/home/ehzhang/PicassoXS/src/backend/flask_app/views/index.py", line 13, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
[2020-04-04 23:01:06 -0400] [7298] [INFO] Worker exiting (pid: 7298)
[2020-04-04 23:01:41 -0400] [7317] [INFO] Starting gunicorn 20.0.4
[2020-04-04 23:01:41 -0400] [7317] [INFO] Listening at: http://127.0.0.1:8000 (7317)
[2020-04-04 23:01:41 -0400] [7317] [INFO] Using worker: sync
[2020-04-04 23:01:41 -0400] [7322] [INFO] Booting worker with pid: 7322
[2020-04-04 23:01:41 -0400] [7323] [INFO] Booting worker with pid: 7323
[2020-04-04 23:02:15 -0400] [7322] [INFO] Worker exiting (pid: 7322)
[2020-04-04 23:02:15 -0400] [7323] [INFO] Worker exiting (pid: 7323)
[2020-04-04 23:02:15 -0400] [7317] [INFO] Handling signal: term
[2020-04-04 23:02:15 -0400] [7317] [INFO] Shutting down: Master
